services:
  mysql-rocket:
    image: mysql:8
    container_name: mysql-rocket
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rocketseat-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - first-network

  api:
    build:
      context: .
    container_name: hello-world
    ports:
      - 3001:3000
    depends_on:
      - mysql-rocket
    networks:
      - first-network

networks:
  first-network:
    name: first-network
    external: true
    driver: bridge
